---
title: "Run CERES"
output: html_notebook
---


```{r}
library(ceres)

### Setup

# Edit this line to point to data directory
data_dir <- "../achilles_pipeline/runs/sanger/achilles_pipeline_run_2018-01-30/ceres/"

cn_seg_file <- file.path(data_dir, "copy_number.txt")
gene_annot_file <- file.path("../achilles_pipeline/data/CCDS_no_compound.txt")

# Set bowtie index directory. Not needed if $BOWTIE_INDEXES environmental variable is set and includes hg19 index.
Sys.setenv(BOWTIE_INDEXES = file.path("../bowtie-master/", "indexes"))


dep_file <- file.path(data_dir, "logfold_change.gct")
rep_map <- file.path(data_dir, "replicate_map.tsv")



### Run CERES

inputs_dir <- file.path(data_dir, "inputs")
```

```{r}
prepare_ceres_inputs(inputs_dir=inputs_dir,
                     dep_file=dep_file,
                     cn_seg_file=cn_seg_file,
                     gene_annot_file=gene_annot_file,
                     rep_map_file=rep_map,
                     chromosomes=paste0("chr", 1:22),
                     dep_normalize="zmad")
```

